# Generated by Django 4.2.5 on 2023-09-18 05:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('climate', models.CharField(choices=[('hot', 'Hot'), ('humid', 'Humid'), ('rainy', 'Rainy'), ('cold', 'Cold')], max_length=10)),
                ('area_code', models.PositiveIntegerField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('chances_of_rain', models.FloatField()),
            ],
        ),
    ]
